version: '3.8'

services:
  web:
    build: .
    container_name: web-stock-jip
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - sqlite_data:/var/www/html/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      # Ensure you configure your other secrets inside Portainer Environment Variables!

volumes:
  sqlite_data:

